---

- name: Setup secure sticky bit
  block:
    - name: Search world writable directories
      ansible.builtin.shell: >-
         set -o pipefail;
         df --local -P | awk {'if (NR!=1) print $6'} \
         | xargs -I '{}' find '{}' -xdev \
         -type d \( -perm -0002 -a ! -perm -1000 \) \
         2>/dev/null
      changed_when: no
      register: secure_sticky_bit_check_result

    - name: Setup sticky bit in world writable directories
      ansible.builtin.shell: >-
        echo "{{ secure_sticky_bit_check_result.stdout }}" | xargs chmod a+t
      when: secure_sticky_bit_check_result.stdout | length != 0
  tags:
    - role::secure_sticky_bit
