---

- name: Prepare
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check testing directory
      ansible.builtin.stat:
        path: /testdir
      register: test_dir_result

    - name: Setup testing directory
      ansible.builtin.file:
        path: /testdir
        state: directory
        mode: 0777
      when: not test_dir_result.stat.exists
